### ISSUE TITLE
Spreadsheet of size 20MB generate java.lang.OutOfMemoryError exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [anarayn/sqlsheet#1]
```
https://groups.google.com/forum/?fromgroups#!topic/scriptella/wr_dkDaQsKQ

When I try to load a spreadsheet that is only 20MB, it uses a massive amount of 
memory and eventually I get a java.lang.OutOfMemoryError exception thrown. I 
went into the scriptella bin and added -Xmx1536m to try and get scriptella to 
use more memory but even with 1.5GB of memory, it stills throws this exception 
on only a 20MB spreadsheet. 

Apr 26, 2012 11:33:18 AM <SEVERE> Script scripts/integration/npcDrop.etl.xml 
execution failed.
Java heap space
Apr 26, 2012 11:33:18 AM <SEVERE> Scriptella bug report. Submit to issue 
tracker.
Scriptella version: 1.1-SNAPSHOT
Exception: 
scriptella.execution.EtlExecutorException: Java heap space
    at scriptella.execution.EtlExecutor.execute(EtlExecutor.java:190)
    at scriptella.tools.launcher.EtlLauncher.execute(EtlLauncher.java:276)
    at scriptella.tools.launcher.EtlLauncher.launch(EtlLauncher.java:193)
    at scriptella.tools.launcher.EtlLauncher.main(EtlLauncher.java:321)
Caused by: java.lang.OutOfMemoryError: Java heap space

```

Original issue reported on code.google.com by `vasilievip` on 30 Apr 2012 at 9:45

**Comment by GoogleCodeExporter** [comment]
Original comment by `vasilievip` on 30 Apr 2012 at 9:46
- Added labels: **Type-Defect**
- Removed labels: **Type-Enhancement**

**Comment by GoogleCodeExporter** [comment]
Original comment by `vasilievip` on 30 Apr 2012 at 9:49
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
This issue was closed by revision r134.
```

Original comment by `vasilievip` on 2 May 2012 at 10:12
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `vasilievip` on 27 Apr 2013 at 7:04
- Added labels: **6.1**
